### ISSUE TITLE
Magento 2 module does not check if picture is already in media gallery

### ISSUE THREAD

**Issue by sebuzi** [cloudinary/cloudinary_magento2#114]
Seems like when adding images with **/V1/cloudinary/products/:sku/media** it does not take to account if the image already exist but adds it again. Checking the method **addGalleryItem** in class **vendor/cloudinary/cloudinary-magento2/Model/Api/ProductGalleryManagement.php** it does not check if its there but just adds.

Am I checking this wrong and if not is there plans to add some kinda checks there or should we implement it by ourself?

Thanks.

**Comment by dannyv-cloudinary** [comment]
Hi Sebuzi.

This is actually done by design. [The vanilla Product Gallery Widget](https://cloudinary.com/documentation/product_gallery) allows you to specify the same asset multiple times if you so wish ((demo jsfiddle)[https://jsfiddle.net/dannyv_cloudinary/djLr8qs9/]), and so we don't prevent users from doing this via the Magento module. If you need to prevent duplication in your gallery, you would need to implement some logic on your side.

Feel free to (raise a support ticket with us)[https://support.cloudinary.com/hc/en-us/requests/new] if we can help with anything else.

Thanks,
-Danny

**Comment by sebuzi** [comment]
Hi Dannyv.

Thanks for the answer. This is clear now so I might make own extend as we need to prevent duplicates when fetching images via API.
