### ISSUE TITLE
How to serve custom images?

### ISSUE THREAD

**Issue by Styopchik** [cloudinary/cloudinary_magento2#49]
By default module serves product images and does not transform cms/description images. How to achieve that?

**Comment by idobarnoam** [comment]
@Styopchik Currently the module indeed innately supports product images and videos.

You could use the Cloudinary links in static blocks and pages directly in order to deliver optimized images from Cloudinary.
As for description images if you could elaborate on your use case and how exactly are you using this we would see how we could further help.

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
