### ISSUE TITLE
Product image transformation is not applied in Magento cloud with Fastly

### ISSUE THREAD

**Issue by reniraj** [cloudinary/cloudinary_magento2#84]
Product image transformation is not applied in Magneto default product image gallery while enable the Fastly in Magento cloud 2.3.5-p2

**Comment by eyalktCloudinary** [comment]
@reniraj Thank you for reaching out! 
It would be easier to investigate this issue via a support ticket, can you please open one via the following link?
https://support.cloudinary.com/hc/en-us/requests/new
Could you also specify some additional details such as -

- Are the images served via Cloudinary and just not transformed?
- Could you share a screenshot of the Cloudinary module's configurations page?
- Is the website public? Can you share a link to a page that shows the issue?
- Our dev team might want to access your environment in order to further investigate. 
Would you be able to provide us with access credentials (via the support ticket) to your environment?

In addition, please specify that you've originally reached out via this GH thread.
